# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

labels:
  app: inventory
  version: v1
  tier: backend
  implementation: microprofile

image:
  repository: ibmcase/inventory-mp
  tag: v2.0.0
  pullPolicy: IfNotPresent
  
resources:
  requests:
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 300Mi

service:
  name: inventory
  type: NodePort
  servicePort: 9080
  servicePortHttps: 9443
  sqlport: 3306
  dbname: inventorydb
  rabbitmq: rabbitmq
  zipkinPort: 9411
  zipkinName: zipkin
  mysql: mysql

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70=

istio:
  enabled: false
  weight: 100
  mTLS: SIMPLE
  gateway:
    enabled: false
    name:
    hosts:
      - "inventory.bluecompute.com"
    TLS:
      enabled: false
      # SIMPLE, MUTUAL
      mode: SIMPLE
      httpsRedirect: false
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/ca-chain.cert.pem

ingress:
  enabled: false
  hostname: #inventory.bluecompute.com
  path: /micro/inventory
  annotations:
    ingress.bluemix.net/redirect-to-https: "True"
  enableTLS: false
  TLS:
  - secretName: inventory.bluecompute.com
    hosts:
      - inventory.bluecompute.com

# For travis
travis: false
jdbcURL: jdbc:mysql://inventory-mysql:3306/inventorydb?useSSL=false
minikubeIp:

mysql:
  host: inventory-mysql
  port: 3306
  existingSecret:
  user: dbuser
  password: password
  database: inventorydb
  # For mysql init container
  image: "mysql"
  imageTag: "5.7.14"
  imagePullPolicy: Always
  istio:
    mTLS: ISTIO_MUTUAL
    loadBalancer: LEAST_CONN